CREATE TABLE `language` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(128) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `locale` varchar(6) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

insert into language(id, name, locale) values(default, 'Afrikaans', 'af') on duplicate key update name = 'Afrikaans', locale = 'af';
insert into language(id, name, locale) values(default, 'Albanian', 'sq') on duplicate key update name = 'Albanian', locale = 'sq';
insert into language(id, name, locale) values(default, 'Amharic', 'am') on duplicate key update name = 'Amharic', locale = 'am';
insert into language(id, name, locale) values(default, 'Arabic', 'ar') on duplicate key update name = 'Arabic', locale = 'ar';
insert into language(id, name, locale) values(default, 'Armenian', 'hy') on duplicate key update name = 'Armenian', locale = 'hy';
insert into language(id, name, locale) values(default, 'Aymara', 'ay') on duplicate key update name = 'Aymara', locale = 'ay';
insert into language(id, name, locale) values(default, 'Azerbaijani', 'az') on duplicate key update name = 'Azerbaijani', locale = 'az';
insert into language(id, name, locale) values(default, 'Basque', 'eu') on duplicate key update name = 'Basque', locale = 'eu';
insert into language(id, name, locale) values(default, 'Fijian', 'fj') on duplicate key update name = 'Fijian', locale = 'fj';
insert into language(id, name, locale) values(default, 'Belarusian', 'be') on duplicate key update name = 'Belarusian', locale = 'be';
insert into language(id, name, locale) values(default, 'Bengali', 'bn') on duplicate key update name = 'Bengali', locale = 'bn';
insert into language(id, name, locale) values(default, 'Punjabi', 'pa') on duplicate key update name = 'Punjabi', locale = 'pa';
insert into language(id, name, locale) values(default, 'Bosnian', 'bs') on duplicate key update name = 'Bosnian', locale = 'bs';
insert into language(id, name, locale) values(default, 'Bulgarian', 'bg') on duplicate key update name = 'Bulgarian', locale = 'bg';
insert into language(id, name, locale) values(default, 'Burmese', 'my') on duplicate key update name = 'Burmese', locale = 'my';
insert into language(id, name, locale) values(default, 'Catalan', 'ca') on duplicate key update name = 'Catalan', locale = 'ca';
insert into language(id, name, locale) values(default, 'Chinese ', 'zh') on duplicate key update name = 'Chinese ', locale = 'zh';
insert into language(id, name, locale) values(default, 'Comorian', 'ch') on duplicate key update name = 'Comorian', locale = 'ch';
insert into language(id, name, locale) values(default, 'Cornish', 'kw') on duplicate key update name = 'Cornish', locale = 'kw';
insert into language(id, name, locale) values(default, 'Croatian', 'hr') on duplicate key update name = 'Croatian', locale = 'hr';
insert into language(id, name, locale) values(default, 'Czech', 'cs') on duplicate key update name = 'Czech', locale = 'cs';
insert into language(id, name, locale) values(default, 'Danish', 'da') on duplicate key update name = 'Danish', locale = 'da';
insert into language(id, name, locale) values(default, 'Dari Persian', 'fa') on duplicate key update name = 'Dari Persian', locale = 'fa';
insert into language(id, name, locale) values(default, 'Dhivehi', 'dv') on duplicate key update name = 'Dhivehi', locale = 'dv';
insert into language(id, name, locale) values(default, 'Dutch', 'nl') on duplicate key update name = 'Dutch', locale = 'nl';
insert into language(id, name, locale) values(default, 'Dzongkha', 'dz') on duplicate key update name = 'Dzongkha', locale = 'dz';
insert into language(id, name, locale) values(default, 'English', 'en') on duplicate key update name = 'English', locale = 'en';
insert into language(id, name, locale) values(default, 'Estonian', 'et') on duplicate key update name = 'Estonian', locale = 'et';
insert into language(id, name, locale) values(default, 'Ewe', 'ee') on duplicate key update name = 'Ewe', locale = 'ee';
insert into language(id, name, locale) values(default, 'Finnish', 'fi') on duplicate key update name = 'Finnish', locale = 'fi';
insert into language(id, name, locale) values(default, 'French', 'fr') on duplicate key update name = 'French', locale = 'fr';
insert into language(id, name, locale) values(default, 'Fulah', 'ff') on duplicate key update name = 'Fulah', locale = 'ff';
insert into language(id, name, locale) values(default, 'Galacian', 'gl') on duplicate key update name = 'Galacian', locale = 'gl';
insert into language(id, name, locale) values(default, 'Ganda', 'lg') on duplicate key update name = 'Ganda', locale = 'lg';
insert into language(id, name, locale) values(default, 'Georgian', 'ka') on duplicate key update name = 'Georgian', locale = 'ka';
insert into language(id, name, locale) values(default, 'German', 'de') on duplicate key update name = 'German', locale = 'de';
insert into language(id, name, locale) values(default, 'Gilbertese', 'gil') on duplicate key update name = 'Gilbertese', locale = 'gil';
insert into language(id, name, locale) values(default, 'Greek', 'el') on duplicate key update name = 'Greek', locale = 'el';
insert into language(id, name, locale) values(default, 'Guarani', 'gn') on duplicate key update name = 'Guarani', locale = 'gn';
insert into language(id, name, locale) values(default, 'Haitian Creole', 'ht') on duplicate key update name = 'Haitian Creole', locale = 'ht';
insert into language(id, name, locale) values(default, 'Hebrew', 'he') on duplicate key update name = 'Hebrew', locale = 'he';
insert into language(id, name, locale) values(default, 'Hindi', 'hi') on duplicate key update name = 'Hindi', locale = 'hi';
insert into language(id, name, locale) values(default, 'Hiri Motu', 'ho') on duplicate key update name = 'Hiri Motu', locale = 'ho';
insert into language(id, name, locale) values(default, 'Hungarian', 'hu') on duplicate key update name = 'Hungarian', locale = 'hu';
insert into language(id, name, locale) values(default, 'Icelandic', 'is') on duplicate key update name = 'Icelandic', locale = 'is';
insert into language(id, name, locale) values(default, 'Indonesian', 'id') on duplicate key update name = 'Indonesian', locale = 'id';
insert into language(id, name, locale) values(default, 'Irish', 'ga') on duplicate key update name = 'Irish', locale = 'ga';
insert into language(id, name, locale) values(default, 'Italian', 'it') on duplicate key update name = 'Italian', locale = 'it';
insert into language(id, name, locale) values(default, 'Japanese', 'ja') on duplicate key update name = 'Japanese', locale = 'ja';
insert into language(id, name, locale) values(default, 'Kazakh', 'kk') on duplicate key update name = 'Kazakh', locale = 'kk';
insert into language(id, name, locale) values(default, 'Khmer', 'km') on duplicate key update name = 'Khmer', locale = 'km';
insert into language(id, name, locale) values(default, 'Kinyarwanda', 'rw') on duplicate key update name = 'Kinyarwanda', locale = 'rw';
insert into language(id, name, locale) values(default, 'Kirundi', 'rn') on duplicate key update name = 'Kirundi', locale = 'rn';
insert into language(id, name, locale) values(default, 'Korean', 'ko') on duplicate key update name = 'Korean', locale = 'ko';
insert into language(id, name, locale) values(default, 'Kurdish', 'ku') on duplicate key update name = 'Kurdish', locale = 'ku';
insert into language(id, name, locale) values(default, 'Kyrgyz', 'ky') on duplicate key update name = 'Kyrgyz', locale = 'ky';
insert into language(id, name, locale) values(default, 'Lao (Laotian)', 'lo') on duplicate key update name = 'Lao (Laotian)', locale = 'lo';
insert into language(id, name, locale) values(default, 'Latvian', 'lv') on duplicate key update name = 'Latvian', locale = 'lv';
insert into language(id, name, locale) values(default, 'Lingala', 'ln') on duplicate key update name = 'Lingala', locale = 'ln';
insert into language(id, name, locale) values(default, 'Lithuanian', 'lt') on duplicate key update name = 'Lithuanian', locale = 'lt';
insert into language(id, name, locale) values(default, 'Macedonian', 'mk') on duplicate key update name = 'Macedonian', locale = 'mk';
insert into language(id, name, locale) values(default, 'Malagasy', 'mg') on duplicate key update name = 'Malagasy', locale = 'mg';
insert into language(id, name, locale) values(default, 'Malay', 'ms') on duplicate key update name = 'Malay', locale = 'ms';
insert into language(id, name, locale) values(default, 'Maltese', 'mt') on duplicate key update name = 'Maltese', locale = 'mt';
insert into language(id, name, locale) values(default, 'Marshallese', 'mh') on duplicate key update name = 'Marshallese', locale = 'mh';
insert into language(id, name, locale) values(default, 'Romanian', 'ro') on duplicate key update name = 'Romanian', locale = 'ro';
insert into language(id, name, locale) values(default, 'Mongolian', 'mn') on duplicate key update name = 'Mongolian', locale = 'mn';
insert into language(id, name, locale) values(default, 'Nauran', 'na') on duplicate key update name = 'Nauran', locale = 'na';
insert into language(id, name, locale) values(default, 'Nepali', 'ne') on duplicate key update name = 'Nepali', locale = 'ne';
insert into language(id, name, locale) values(default, 'North Ndebele', 'nd') on duplicate key update name = 'North Ndebele', locale = 'nd';
insert into language(id, name, locale) values(default, 'Northern Sami', 'se') on duplicate key update name = 'Northern Sami', locale = 'se';
insert into language(id, name, locale) values(default, 'Norwegian', 'no') on duplicate key update name = 'Norwegian', locale = 'no';
insert into language(id, name, locale) values(default, 'Ossetic', 'os') on duplicate key update name = 'Ossetic', locale = 'os';
insert into language(id, name, locale) values(default, 'Palauan', 'pau') on duplicate key update name = 'Palauan', locale = 'pau';
insert into language(id, name, locale) values(default, 'Pashto', 'ps') on duplicate key update name = 'Pashto', locale = 'ps';
insert into language(id, name, locale) values(default, 'Persian', 'fa') on duplicate key update name = 'Persian', locale = 'fa';
insert into language(id, name, locale) values(default, 'Polish', 'pl') on duplicate key update name = 'Polish', locale = 'pl';
insert into language(id, name, locale) values(default, 'Portuguese', 'pt') on duplicate key update name = 'Portuguese', locale = 'pt';
insert into language(id, name, locale) values(default, 'Quechua', 'qu') on duplicate key update name = 'Quechua', locale = 'qu';
insert into language(id, name, locale) values(default, 'Romansh', 'rm') on duplicate key update name = 'Romansh', locale = 'rm';
insert into language(id, name, locale) values(default, 'Russian', 'ru') on duplicate key update name = 'Russian', locale = 'ru';
insert into language(id, name, locale) values(default, 'Sango', 'sg') on duplicate key update name = 'Sango', locale = 'sg';
insert into language(id, name, locale) values(default, 'Scottish Gaelic', 'gd') on duplicate key update name = 'Scottish Gaelic', locale = 'gd';
insert into language(id, name, locale) values(default, 'Serbian', 'sr') on duplicate key update name = 'Serbian', locale = 'sr';
insert into language(id, name, locale) values(default, 'Sesotho', 'st') on duplicate key update name = 'Sesotho', locale = 'st';
insert into language(id, name, locale) values(default, 'Seychellois Creole', 'crs') on duplicate key update name = 'Seychellois Creole', locale = 'crs';
insert into language(id, name, locale) values(default, 'Shona', 'sn') on duplicate key update name = 'Shona', locale = 'sn';
insert into language(id, name, locale) values(default, 'Sichuan Yi', 'ii') on duplicate key update name = 'Sichuan Yi', locale = 'ii';
insert into language(id, name, locale) values(default, 'Slovak', 'sk') on duplicate key update name = 'Slovak', locale = 'sk';
insert into language(id, name, locale) values(default, 'Slovenian', 'sl') on duplicate key update name = 'Slovenian', locale = 'sl';
insert into language(id, name, locale) values(default, 'Somali', 'so') on duplicate key update name = 'Somali', locale = 'so';
insert into language(id, name, locale) values(default, 'Spanish', 'es') on duplicate key update name = 'Spanish', locale = 'es';
insert into language(id, name, locale) values(default, 'Swahili', 'sw') on duplicate key update name = 'Swahili', locale = 'sw';
insert into language(id, name, locale) values(default, 'Swedish', 'sv') on duplicate key update name = 'Swedish', locale = 'sv';
insert into language(id, name, locale) values(default, 'Tagalog', 'tl') on duplicate key update name = 'Tagalog', locale = 'tl';
insert into language(id, name, locale) values(default, 'Tajik', 'tg') on duplicate key update name = 'Tajik', locale = 'tg';
insert into language(id, name, locale) values(default, 'Tamazight', 'tzm') on duplicate key update name = 'Tamazight', locale = 'tzm';
insert into language(id, name, locale) values(default, 'Tamil', 'ta') on duplicate key update name = 'Tamil', locale = 'ta';
insert into language(id, name, locale) values(default, 'Thai', 'th') on duplicate key update name = 'Thai', locale = 'th';
insert into language(id, name, locale) values(default, 'Tibetan', 'bo') on duplicate key update name = 'Tibetan', locale = 'bo';
insert into language(id, name, locale) values(default, 'Tigrinya', 'ti') on duplicate key update name = 'Tigrinya', locale = 'ti';
insert into language(id, name, locale) values(default, 'Tok Pisin', 'tpi') on duplicate key update name = 'Tok Pisin', locale = 'tpi';
insert into language(id, name, locale) values(default, 'Tongan', 'to') on duplicate key update name = 'Tongan', locale = 'to';
insert into language(id, name, locale) values(default, 'Tswana', 'tn') on duplicate key update name = 'Tswana', locale = 'tn';
insert into language(id, name, locale) values(default, 'Turkish', 'tr') on duplicate key update name = 'Turkish', locale = 'tr';
insert into language(id, name, locale) values(default, 'Turkmen', 'tk') on duplicate key update name = 'Turkmen', locale = 'tk';
insert into language(id, name, locale) values(default, 'Ukrainian', 'uk') on duplicate key update name = 'Ukrainian', locale = 'uk';
insert into language(id, name, locale) values(default, 'Urdu', 'ur') on duplicate key update name = 'Urdu', locale = 'ur';
insert into language(id, name, locale) values(default, 'Uyghur', 'ug') on duplicate key update name = 'Uyghur', locale = 'ug';
insert into language(id, name, locale) values(default, 'Uzbek', 'uz') on duplicate key update name = 'Uzbek', locale = 'uz';
insert into language(id, name, locale) values(default, 'Vietnamese', 'vi') on duplicate key update name = 'Vietnamese', locale = 'vi';
insert into language(id, name, locale) values(default, 'Welsh', 'cy') on duplicate key update name = 'Welsh', locale = 'cy';
insert into language(id, name, locale) values(default, 'Zulu', 'zu') on duplicate key update name = 'Zulu', locale = 'zu';
insert into language(id, name, locale) values(default, 'Marathi', 'mr') on duplicate key update name = 'Marathi', locale = 'mr';
insert into language(id, name, locale) values(default, 'Telugu', 'te') on duplicate key update name = 'Telugu', locale = 'te';
insert into language(id, name, locale) values(default, 'Tamil', 'ta') on duplicate key update name = 'Tamil', locale = 'ta';
insert into language(id, name, locale) values(default, 'Gujarati', 'gu') on duplicate key update name = 'Gujarati', locale = 'gu';