--CREATE TABLE users (
--	`id` bigint NOT NULL AUTO_INCREMENT,
--	`email` varchar(254) NOT NULL,
--	`created_at` timestamp DEFAULT current_timestamp(),
--	`updated_at` timestamp DEFAULT current_timestamp(),
--	`first_name` varchar(32) DEFAULT '',
--	`last_name`  varchar(32) DEFAULT '',
--	`phone_country_code` varchar(6),
--	`phone_number` varchar(16),
--	`address` varchar(254) NOT NULL DEFAULT '',
--	`post_code` varchar(16) NOT NULL DEFAULT '',
--	`city` varchar(64) NOT NULL DEFAULT '',
--	`status` varchar(20) NOT NULL DEFAULT 'UNCONFIRMED',
--	`email_verified` varchar(20) NOT NULL DEFAULT 'UNVERIFIED',
--	`phone_verified` varchar(20) NOT NULL DEFAULT 'UNVERIFIED',
--	`preferred_language_id` int NOT NULL,
--	`google_account_id` bigint,
--	`facebook_account_id` bigint,
--	`authentication_method` varchar(20) NOT NULL DEFAULT 'PASSWORD',
--	`device_token` varchar(64)  NOT NULL,
--  PRIMARY KEY (`id`),
--	CONSTRAINT `uk_users_email` UNIQUE (`email`),
--	CONSTRAINT `uk_users_username` UNIQUE (`username`) ,
--	CONSTRAINT `user_ibfk_1` FOREIGN KEY (`country_id`) REFERENCES country(`id`),
--	CONSTRAINT `user_preferred_language__fk_0` FOREIGN KEY (`preferred_language_id`) REFERENCES language(`id`),
--	CONSTRAINT `fk_facebook_account_0` FOREIGN KEY (`facebook_account_id`) REFERENCES social_account(`id`),
--	CONSTRAINT `fk_google_account_0` FOREIGN KEY (`google_account_id`) REFERENCES social_account(`id`)
--) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE users (
	`id` bigint NOT NULL AUTO_INCREMENT,
	`email` varchar(254) NOT NULL,
	`password` varchar(100),
	`created_at` timestamp DEFAULT current_timestamp(),
	`updated_at` timestamp DEFAULT current_timestamp(),
	`first_name` varchar(32) DEFAULT '',
	`last_name`  varchar(32) DEFAULT '',
	`birthdate` timestamp DEFAULT current_timestamp(),
	`phone_country_code` varchar(6),
	`phone_number` varchar(16),
	`phone_verification_code` varchar(6),
	`phone_verification_code_created_at` timestamp DEFAULT current_timestamp(),
	`address` varchar(254) NOT NULL DEFAULT '',
	`post_code` varchar(16) NOT NULL DEFAULT '',
	`city` varchar(64) NOT NULL DEFAULT '',
	`status` varchar(20) NOT NULL DEFAULT 'UNCONFIRMED',
	`email_verified` varchar(20) NOT NULL DEFAULT 'UNVERIFIED',
	`phone_verified` varchar(20) NOT NULL DEFAULT 'UNVERIFIED',
	`preferred_language_id` bigint NOT NULL,
	`authentication_method` varchar(20) NOT NULL DEFAULT 'PASSWORD',
	`country_id` bigint DEFAULT NULL,
	`device_token` varchar(64) NOT NULL,
	PRIMARY KEY (`id`),
	CONSTRAINT `uk_user_email` UNIQUE (`email`),
	CONSTRAINT `user_preferred_language__fk_0` FOREIGN KEY (`preferred_language_id`) REFERENCES language(`id`),
	CONSTRAINT `user_country_id_fk` FOREIGN KEY (`country_id`) REFERENCES country(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;