CREATE TABLE offer (
	`id` bigint NOT NULL AUTO_INCREMENT,
	`chef_id` bigint NOT NULL,
	`offer_type` varchar(20) NOT NULL,
	`status` varchar(20) NOT NULL,
	`title` varchar(64) NOT NULL DEFAULT '',
	`description` varchar(512) NOT NULL DEFAULT '',
	`weight` int DEFAULT 0,
	`serving_address` varchar(128),
	`serving_postcode` varchar(16),
	`serving_city` varchar(64),
	`latitude` decimal(8,6),
	`longitude` decimal(8,6),
	`serving_start` datetime,
	`serving_end` datetime,
	`order_until` datetime,
	`price` decimal(8,2) UNSIGNED NOT NULL DEFAULT 0.00,
	`max_quantity` int UNSIGNED,
	`quantity_available` int UNSIGNED,
	`is_pickup` boolean NOT NULL,
	`is_delivery` boolean NOT NULL,
	`min_free_delivery_amount` decimal(8,2) UNSIGNED,
	`min_preorder_hours` int UNSIGNED,
	`zone1_max_distance` decimal(8,2) UNSIGNED,
	`zone1_delivery_price` decimal(8,2) UNSIGNED,
	`zone2_max_distance` decimal(8,2) UNSIGNED,
	`zone2_delivery_price` decimal(8,2) UNSIGNED,
	`zone3_max_distance` decimal(8,2) UNSIGNED,
	`zone3_delivery_price` decimal(8,2) UNSIGNED,
	`offer_picture1` varchar(256) DEFAULT NULL,
	`offer_picture2` varchar(256) DEFAULT NULL,
	`offer_picture3` varchar(256) DEFAULT NULL,
	`created_at` timestamp DEFAULT current_timestamp(),
	`updated_at` timestamp DEFAULT current_timestamp(),
	PRIMARY KEY (`id`),
	CONSTRAINT fk_offer_chef_id FOREIGN KEY (`chef_id` ) REFERENCES chef(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;